package app.uperf.manager

import com.topjohnwu.superuser.Shell
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/** Root shell + uperf 配置文件读写 */
object UperfRepo {

    const val USER_PATH = "/sdcard/Android/yc/uperf"
    const val PERAPP = "$USER_PATH/perapp_powermode.txt"
    const val CURMODE = "$USER_PATH/cur_powermode.txt"
    const val UJSON = "$USER_PATH/uperf.json"
    const val LOG = "$USER_PATH/uperf_log.txt"
    const val MODULE_PROP = "/data/adb/modules/uperf/module.prop"

    val MODE_CN = mapOf(
        "auto" to "动态", "powersave" to "省电", "balance" to "均衡",
        "performance" to "性能", "fast" to "极速", "crazy" to "极速"
    )

    init {
        Shell.enableVerboseLogging = false
        Shell.setDefaultBuilder(
            Shell.Builder.create().setFlags(Shell.FLAG_MOUNT_MASTER).setTimeout(10)
        )
    }

    /** 主动请求 root shell 并用 id 实测（KernelSU 下 isAppGrantedRoot 未请求前恒为 null） */
    fun checkRoot(): Boolean {
        return try {
            Shell.getShell() // 触发 KernelSU/Magisk 授权弹窗
            Shell.cmd("id -u").exec().out.firstOrNull()?.trim() == "0"
        } catch (e: Exception) {
            false
        }
    }

    fun sh(cmd: String): String =
        Shell.cmd(cmd).exec().out.joinToString("\n")

    // ---------- 全局模式 ----------
    fun getCurMode(): String =
        sh("cat $CURMODE").trim().ifBlank { "auto" }

    fun setCurMode(mode: String) {
        sh("echo $mode > $CURMODE")
    }

    // ---------- 分应用规则 ----------
    data class Perapp(
        val rules: MutableMap<String, String> = linkedMapOf(),
        var offscreen: String = "powersave",
        var fallback: String = "balance"
    )

    fun getPerapp(): Perapp {
        val p = Perapp()
        sh("cat $PERAPP").lines().forEach { raw ->
            val l = raw.trim()
            if (l.isEmpty() || l.startsWith("#")) return@forEach
            val i = l.indexOfFirst { it.isWhitespace() }
            if (i < 0) return@forEach
            val key = l.substring(0, i).trim()
            val mode = l.substring(i).trim()
            when (key) {
                "-" -> p.offscreen = mode
                "*" -> p.fallback = mode
                else -> p.rules[key] = mode
            }
        }
        return p
    }

    fun savePerapp(p: Perapp) {
        val sb = StringBuilder("# 分应用性能模式配置\n# Generated by Uperf Manager\n\n")
        p.rules.forEach { (pkg, mode) -> sb.append("$pkg $mode\n") }
        sb.append("- ${p.offscreen}\n* ${p.fallback}\n")
        val b64 = android.util.Base64.encodeToString(
            sb.toString().toByteArray(), android.util.Base64.NO_WRAP
        )
        sh("echo $b64 | base64 -d > $PERAPP")
    }

    // ---------- 日志级别 ----------
    fun getLogLevel(): String {
        val out = sh("grep -o '\"level\"[^,}]*' $UJSON | head -1")
        return Regex("\"(debug|info|error)\"", RegexOption.IGNORE_CASE)
            .find(out)?.groupValues?.get(1)?.lowercase() ?: "info"
    }

    fun setLogLevel(lv: String) {
        sh("sed -i 's/\"level\"[ ]*:[ ]*\"[a-z]*\"/\"level\": \"$lv\"/i' $UJSON")
    }

    fun getLog(): String = sh("tail -c 8192 $LOG")

    // ---------- 模块信息 ----------
    fun getModuleProp(key: String): String =
        sh("grep '^$key=' $MODULE_PROP | cut -d= -f2-").trim()

    fun isRunning(): Boolean = sh("pgrep -x uperf").isNotBlank()

    fun restart() {
        sh("killall uperf 2>/dev/null; sh /data/adb/modules/uperf/script/initsvc.sh >/dev/null 2>&1 &")
    }

    fun uninstall() {
        sh("touch /data/adb/modules/uperf/remove")
    }

    fun reboot() {
        sh("svc power reboot || reboot")
    }
}

/** 应用列表（轻量加载；图标由 IconCache 在 UI 层异步按需加载） */
data class AppEntry(
    val pkg: String,
    val label: String,
    val isSystem: Boolean
)

private val zhCollator = java.text.Collator.getInstance(java.util.Locale.CHINA)

suspend fun loadInstalledApps(pm: android.content.pm.PackageManager): List<AppEntry> =
    withContext(Dispatchers.IO) {
        pm.getInstalledApplications(android.content.pm.PackageManager.MATCH_ALL)
            .filter { it.enabled && it.packageName != "app.uperf.manager" }
            .map {
                AppEntry(
                    pkg = it.packageName,
                    label = runCatching { it.loadLabel(pm).toString() }.getOrDefault(it.packageName),
                    isSystem = it.flags and android.content.pm.ApplicationInfo.FLAG_SYSTEM != 0
                )
            }
            .sortedWith(compareBy({ it.isSystem }, { zhCollator.getCollationKey(it.label) }))
    }
